### ISSUE TITLE
DNS not propagating

### ISSUE THREAD

**Issue by AppleTechy** [wdouglascampbell/dehydrated_namecheap_dns_api_hook#7]
Let me just start off by saying this is probably a stupid question. When running dehydrated to the staging environment will this script not populate the DNS? I uploaded the debug log to pastebin. I think something is happening with their api refusing some protocol you are using? [PasteBin Link](https://pastebin.com/7Lxx4tPg)

**Comment by wdouglascampbell** [comment]
Sorry I didn't see this until now and the PasteBin link you provided isn't valid any longer.  The script works for me both in production and staging and yes it interacts with the DNS making temporary changes to provide verification of ownership.

**Comment by AppleTechy** [comment]
Hmm weird ok. I’ll have to see if I can get the log for the script again. I ended up just switching over to CloudFlare’s DNS so I could use the hook for Cloudflare. Thanks for confirming about the staging and production environment.

**Comment by yakut-dev** [comment]
@wdouglascampbell 
This script successfully propagates the DNS, but it hangs on "DNS not progagated..." for the full 30 minutes. I can see the TXT entry in my namecheap dashboard, but the script does not retrieve it. Ideas?

**Comment by wdouglascampbell** [comment]
> @wdouglascampbell
> This script successfully propagates the DNS, but it hangs on "DNS not progagated..." for the full 30 minutes. I can see the TXT entry in my namecheap dashboard, but the script does not retrieve it. Ideas?

I have encountered this occasionally.  Sometimes I have just waited until my scheduled task runs again the next day and all works out fine but if I feel inclined to get it working right away I have found success by going and telling Cloudfare to purge its cache of the TXT record for the problem domain.  You can do that here:  https://1.1.1.1/purge-cache/

Once I do that everything seems to work as expected the next run.
